<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>io.github.trethore</groupId>
    <artifactId>jcefgithub-parent</artifactId>
    <version>${revision}</version>
    <packaging>pom</packaging>
    <properties>
        <revision>146.0.10.1-SNAPSHOT</revision>
        <jcef.version>jcef-36f2966+cef-143.0.14+gdd46a37+chromium-143.0.7499.193</jcef.version>
        <maven.compiler.release>17</maven.compiler.release>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>
    <modules><module>library</module></modules>
</project>
