name: github-release

on:
  workflow_call:
    inputs:
      build_meta:
        required: true
        type: string
      mvn_version:
        required: false
        type: string
        default: '1.0.0'
  workflow_dispatch:
    inputs:
      build_meta:
        description: 'Build meta to use as source'
        required: true
      mvn_version:
        description: 'Maven version to use'
        required: false
        default: '1.0.0'

jobs:
  github-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    env:
      BUILD_META: ${{ inputs.build_meta || github.event.inputs.build_meta }}
      MVN_VERSION: ${{ inputs.mvn_version || github.event.inputs.mvn_version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Create artifacts
        run: chmod +x generate_artifacts.sh && ./generate_artifacts.sh "$BUILD_META" "$MVN_VERSION"
      - name: Publish to GitHub Packages
        run: chmod +x upload_artifacts.sh && ./upload_artifacts.sh "$BUILD_META" "$MVN_VERSION"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
      - name: Update README.md
        run: |
          chmod +x update_readme.sh
          ./update_readme.sh "$BUILD_META" "$MVN_VERSION"
      - name: Generate release info
        run: |
          cd scripts
          chmod +x create_release_info.sh
          ./create_release_info.sh "$BUILD_META" https://github.com/${{github.repository}}/actions/runs/${{github.run_id}} ${{github.run_number}} "$MVN_VERSION"
      - name: Create Release
        run: |
          gh release create ${{env.release_tag_name}} --title "${{env.release_name}}" --notes-file release_info/release_message.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Add build_meta.json
        run: |
          gh release upload ${{env.release_tag_name}} release_info/build_meta.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload artifacts to GitHub release
        run: |
          cd out
          gh release upload ${{env.release_tag_name}} $(find . -type f -name "*.jar" -printf "%p ")
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
