name: release

on:
  workflow_dispatch:
    inputs:
      build_meta:
        description: 'Build meta to use as source'
        required: true
      mvn_version:
        description: 'Maven version to use'
        required: false
        default: '1.0.0'
      publish_target:
        description: 'Where to publish artifacts'
        required: true
        default: both
        type: choice
        options:
          - both
          - github
          - maven

jobs:
  github-release:
    if: ${{ github.event.inputs.publish_target == 'both' || github.event.inputs.publish_target == 'github' }}
    uses: ./.github/workflows/github-release.yml
    with:
      build_meta: ${{ github.event.inputs.build_meta }}
      mvn_version: ${{ github.event.inputs.mvn_version }}
    secrets: inherit

  maven-release:
    if: ${{ github.event.inputs.publish_target == 'both' || github.event.inputs.publish_target == 'maven' }}
    uses: ./.github/workflows/maven-release.yml
    with:
      build_meta: ${{ github.event.inputs.build_meta }}
      mvn_version: ${{ github.event.inputs.mvn_version }}
    secrets: inherit
